schedule_tracker/config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'login' => 'login#index', as: :login

  get 'login' => 'login#authenticate', as: :authenticate

  get 'logout' => 'login#logout', as: :logout

  get '/' => 'home#index', as: :home

  root 'home#index'

  resources :professors
  resources :prossefors
  resources :courses
  resources :registrations
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

schedule_tracker/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  # def authenticate
  #   @user = User.find_by username: params[:username], password: params[:password]
  #
  #   # create flash messages and redirect based on login success
  #   if @user
  #     flash[:message] = "You have been logged in."
  #
  #     # set user id as session param, accessible to entire app
  #     session[:user_id] = @user.id
  #     redirect_to home_path
  #   else
  #     flash[:message] = "You have not been logged in. User cannot be found."
  #     redirect_to login_path
  #   end
  # end

  # def logout
  #   session[:user_id] = nil
  #   flash[:message] = "You have been logged out."
  #   redirect_to login_path
  # end
end

schedule_tracker/app/helpers/login_helper.rb
module LoginHelper
end

schedule_tracker/app/views/login/authenticate.html.erb
<h1>Login#authenticate</h1>
<p>Find me in app/views/login/authenticate.html.erb</p>

schedule_tracker/app/views/login/index.html.erb
<h1>Login</h1>

<%= form_tag authenticate_path do %>
  <p>
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </p>

  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= submit_tag :login %>
  </p>
<% end %>

schedule_tracker/app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>