schedule_tracker/config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'login' => 'login#index', as: :login

  get 'login' => 'login#authenticate', as: :authenticate

  get 'logout' => 'login#logout', as: :logout

  get '/' => 'home#index', as: :home

  root 'home#index'

  resources :professors
  resources :prossefors
  resources :courses
  resources :registrations
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

schedule_tracker/app/models/student.rb
class Student < ApplicationRecord


  validates :f_name, :l_name, :grad_yr, presence: true
  validates :grad_yr, numericality: true

  def net_id
    "#{l_name}#{f_name[0..1]}"
  end

  belongs_to :classes, through: :Registration


  scope :by_alpha, -> { order(:l_name, :f_name) }
  scope :by_year, -> { order(:grad_yr)}


end

schedule_tracker/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:f_name, :l_name, :grad_yr)
    end
end

schedule_tracker/app/helpers/students_helper.rb
module StudentsHelper
end

schedule_tracker/app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :f_name %>
    <%= f.text_field :f_name %>
  </div>

  <div class="field">
    <%= f.label :l_name %>
    <%= f.text_field :l_name %>
  </div>

  <div class="field">
    <%= f.label :grad_yr %>
    <%= f.number_field :grad_yr %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

schedule_tracker/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

schedule_tracker/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th>L name</th>
      <th>Grad yr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.f_name %></td>
        <td><%= student.l_name %></td>
        <td><%= student.grad_yr %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Remove', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

schedule_tracker/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

schedule_tracker/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @student.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @student.l_name %>
</p>

<p>
  <strong>Grad yr:</strong>
  <%= @student.grad_yr %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>